PackageIdentifier: Keelstrap.Keelstrap
PackageVersion: 1.1.1
Installers:
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://gitlab.com/entayga/keelstrap/-/releases/v1.1.1/downloads/Keelstrap.exe
  InstallerSha256: F496F609CE590F72A9AEF23AB46C7AFDBEBA71B132BDB82E1DB228935A5B1E05
  Commands:
  - keelstrap
ManifestType: installer
ManifestVersion: 1.6.0