PackageIdentifier: Keelstrap.Keelstrap
PackageVersion: 1.1.1
PackageLocale: en-US
Publisher: Keelstrap
PackageName: Keelstrap
PackageUrl: https://gitlab.com/entayga/keelstrap
License: LGPL-3.0-or-later
ShortDescription: Roblox bootstrapper with fastflags, mods, cleaner and doctor tools.
Moniker: keelstrap
ManifestType: defaultLocale
ManifestVersion: 1.6.0